[package]
name = "hop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = { version = "4.0" }
regex = { version = "1.5" }
tokio-tar = { version = "0.3" }
structopt = { version = "0.3" }
gitignore = { version = "1.0" }
dialoguer = { version = "0.10" }
webbrowser = { version = "0.7" }
portpicker = { version = "0.1" }
serde_yaml = { version = "0.8" }
serde_json = { version = "1.0" }
querystring = { version = "1.1" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14", features = ["server"] }
reqwest = { version = "0.11", features = ["json"] }
async-compression = { version = "0.3", features = ["tokio", "gzip"] }
